[server]
address = "127.0.0.1"
port = 8000
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8000

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#1677FF"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"
